BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "videos" (
	"id"	INTEGER,
	"status"	TEXT NOT NULL,
	"file_key"	TEXT NOT NULL UNIQUE,
	"created_at"	INTEGER NOT NULL,
	"modified_at"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
